import { DarkTheme as NavigationDarkTheme } from '@react-navigation/native';
import { MD3DarkTheme as PaperDarkTheme } from 'react-native-paper';
import { CMAIUtil } from '@/Utils';

const DarkTheme = {
  ...NavigationDarkTheme,
  ...PaperDarkTheme,
  colors: {
    ...NavigationDarkTheme.colors,
    ...PaperDarkTheme.colors,
    // recommended/generated by rn paper
    // primary: 'rgb(207, 188, 255)',
    // onPrimary: 'rgb(56, 28, 118)',
    // primary: 'rgb(151, 130, 195)', // light

    // primary: 'rgb(104, 79, 168)',
    primary: '#FFCD05', //brand color yellow
    primaryLight: 'rgb(48, 45, 55)', // level 4
    primaryDark: 'rgb(151, 130, 195)', // light purple
    primaryLight2: 'rgb(42, 40, 48)', // level 2
    onPrimary: 'rgb(255, 255, 255)',

    primaryContainer: 'rgb(79, 54, 142)',
    onPrimaryContainer: 'rgb(233, 221, 255)',
    secondary: 'rgb(204, 194, 219)',
    onSecondary: 'rgb(51, 45, 65)',
    secondaryContainer: 'rgb(74, 68, 88)',
    onSecondaryContainer: 'rgb(232, 222, 248)',
    tertiary: 'rgb(239, 184, 200)',
    onTertiary: 'rgb(74, 37, 50)',
    tertiaryContainer: 'rgb(99, 59, 72)',
    onTertiaryContainer: 'rgb(255, 217, 227)',
    error: 'rgb(255, 180, 171)',
    onError: 'rgb(105, 0, 5)',
    errorContainer: 'rgb(147, 0, 10)',
    onErrorContainer: 'rgb(255, 180, 171)',
    background: 'rgb(28, 27, 30)',
    onBackground: 'rgb(230, 225, 230)',
    surface: 'rgb(28, 27, 30)',
    onSurface: 'rgb(230, 225, 230)',
    surfaceVariant: 'rgb(73, 69, 78)',
    onSurfaceVariant: 'rgb(202, 196, 207)',
    outline: 'rgb(148, 143, 153)',
    outlineVariant: 'rgb(73, 69, 78)',
    shadow: 'rgb(0, 0, 0)',
    scrim: 'rgb(0, 0, 0)',
    inverseSurface: 'rgb(230, 225, 230)',
    inverseOnSurface: 'rgb(49, 48, 51)',
    inversePrimary: 'rgb(104, 79, 168)',
    elevation: {
      level0: 'transparent',
      level1: 'rgb(37, 35, 41)',
      level2: 'rgb(42, 40, 48)',
      level3: 'rgb(48, 45, 55)',
      level4: 'rgb(50, 46, 57)',
      level5: 'rgb(53, 50, 62)',
    },
    surfaceDisabled: 'rgba(230, 225, 230, 0.12)',
    onSurfaceDisabled: 'rgba(230, 225, 230, 0.38)',
    backdrop: 'rgba(50, 47, 56, 0.4)',

    brand: '#E8BF46',
    brandLight: '#FFDF80',

    onBrand: 'rgb(64, 45, 0)',
    brandContainer: 'rgb(92, 67, 0)',
    onBrandContainer: 'rgb(255, 223, 160)',
    skeleton: 'rgb(50, 46, 57)',
    skeletonHighlight: 'rgb(37, 35, 41)',
  },
  roundness: 2,
};
// const DarkTheme = {
//   ...NavigationDarkTheme,
//   ...PaperDarkTheme,

// };

export default DarkTheme;
